export const MAIN_API = 'https://s15-13-ft-java-react-deploy.up.railway.app'
export const ROUTE_LOGIN = '/api/user/login'
export const ROUTE_PURCHASES = '/api/purchase'
export const ROUTE_PRODUCT = '/api/product'
export const ROUTE_SUPPLIER = '/api/supplier'
export const ROUTE_ALL_SALES = '/api/sale/getbydate'
